"""
Inspect both dataset CSVs and write findings to data/schema/data_dictionary.md.

Usage:
    python scripts/inspect_schema.py

Outputs:
    data/schema/data_dictionary.md
"""

import sys
import ast
import textwrap
from pathlib import Path
from collections import Counter
from datetime import datetime

import pandas as pd

sys.path.insert(0, str(Path(__file__).parent.parent))
from config.settings import (
    EXERCISES_CSV,
    PROGRAMS_CSV,
    DATA_SCHEMA_DIR,
)

OUT_PATH = DATA_SCHEMA_DIR / "data_dictionary.md"


def safe_parse_list(val):
    try:
        result = ast.literal_eval(val)
        return result if isinstance(result, list) else [result]
    except Exception:
        return [val] if pd.notna(val) else []


def null_table(df: pd.DataFrame) -> str:
    rows = []
    for col in df.columns:
        n = df[col].isnull().sum()
        pct = n / len(df) * 100
        rows.append(f"| `{col}` | {n:,} | {pct:.2f}% |")
    return "\n".join(rows)


def numeric_stats(df: pd.DataFrame, cols: list) -> str:
    desc = df[cols].describe().round(2)
    lines = ["| stat | " + " | ".join(cols) + " |"]
    lines.append("|---|" + "---|" * len(cols))
    for stat in desc.index:
        vals = " | ".join(str(desc.loc[stat, c]) for c in cols)
        lines.append(f"| {stat} | {vals} |")
    return "\n".join(lines)


def value_counts_table(series: pd.Series, top_n: int = 20) -> str:
    vc = series.value_counts(dropna=False).head(top_n)
    rows = []
    total = len(series)
    for val, cnt in vc.items():
        pct = cnt / total * 100
        rows.append(f"| `{val}` | {cnt:,} | {pct:.1f}% |")
    return "\n".join(rows)


def list_col_counts(series: pd.Series) -> str:
    counts = Counter(v for cell in series for v in safe_parse_list(cell))
    rows = []
    total_programs = len(series)
    for val, cnt in counts.most_common():
        pct = cnt / total_programs * 100
        rows.append(f"| `{val}` | {cnt:,} | {pct:.1f}% |")
    return "\n".join(rows)


def main() -> None:
    print("Loading CSVs …")
    detail  = pd.read_csv(EXERCISES_CSV)
    summary = pd.read_csv(PROGRAMS_CSV)

    detail["is_time_based"] = detail["reps"] < 0
    detail["reps_abs"]      = detail["reps"].abs()

    rep_based  = detail[~detail["is_time_based"]]
    time_based = detail[detail["is_time_based"]]

    unique_programs  = detail["title"].nunique()
    unique_exercises = detail["exercise_name"].nunique()

    lines = []

    # ── Header ────────────────────────────────────────────────────────────────
    lines += [
        "# Data Dictionary — 600K Fitness Exercise & Workout Program Dataset",
        "",
        f"> Generated by `scripts/inspect_schema.py` on {datetime.now().strftime('%Y-%m-%d %H:%M')}.",
        "> Re-run this script if the dataset is updated.",
        "",
        "## Files",
        "",
        f"| File | Rows | Columns | Size |",
        f"|---|---|---|---|",
        f"| `programs_detailed_boostcamp_kaggle.csv` | {len(detail):,} | {detail.shape[1]} | exercise-level, one row per exercise per day per week per program |",
        f"| `program_summary.csv` | {len(summary):,} | {summary.shape[1]} | program-level, one row per program |",
        "",
        f"**Unique programs in detail file:** {unique_programs:,}  ",
        f"**Unique exercise names in detail file:** {unique_exercises:,}",
        "",
        "---",
        "",
    ]

    # ── programs_detailed ─────────────────────────────────────────────────────
    lines += [
        "## `programs_detailed_boostcamp_kaggle.csv` — column reference",
        "",
        "### Column overview",
        "",
        "| Column | dtype | Description | Notes |",
        "|---|---|---|---|",
        "| `title` | str | Program name — shared across all exercise rows of a program | Acts as a foreign key back to `program_summary` |",
        "| `description` | str | Program narrative description | Shared across rows of same program; ~0.14% null |",
        "| `level` | str | Stringified Python list of difficulty levels | Parse with `ast.literal_eval`; values: Beginner/Novice/Intermediate/Advanced |",
        "| `goal` | str | Stringified Python list of training goals | Parse with `ast.literal_eval`; 8 possible values |",
        "| `equipment` | str | Equipment category required | 4 values + rare NaN; exact-match filter safe |",
        "| `program_length` | float | Total program duration in weeks | Integer values 1–18; ~0.003% null |",
        "| `time_per_workout` | float | Expected workout duration in minutes | Range 10–180; no nulls |",
        "| `week` | float | Week number within the program | 1-indexed; range 1–18 |",
        "| `day` | float | Day number within the week | 1-indexed; range 1–10 |",
        "| `number_of_exercises` | float | Exercises scheduled for this day | Range 1–24 |",
        "| `exercise_name` | str | Name of the exercise | 3,213 unique names |",
        "| `sets` | float | Number of sets prescribed | Range 1–30; median 3 |",
        "| `reps` | float | Reps **or** negative seconds for time-based exercises | Negative = time-based: e.g. -180 = 180 s. Use `abs(reps)` + `is_time_based` flag |",
        "| `intensity` | float | Perceived intensity on 0–10 scale | Integer values 0–10; no nulls |",
        "| `created` | str | Program creation timestamp | Format: `YYYY-MM-DD HH:MM:SS` |",
        "| `last_edit` | str | Last edit timestamp | ~0.01% null |",
        "",
        "### Missing values",
        "",
        "| Column | Null count | Null % |",
        "|---|---|---|",
        null_table(detail),
        "",
        "### Numeric column statistics",
        "",
        "#### Program-level fields (same value repeated for all rows of a program)",
        "",
        numeric_stats(detail, ["program_length", "time_per_workout", "week", "day"]),
        "",
        "#### Exercise-level fields",
        "",
        numeric_stats(detail, ["number_of_exercises", "sets", "intensity"]),
        "",
        "#### Reps — rep-based only (reps > 0)",
        "",
        f"Rows: {len(rep_based):,}",
        "",
        numeric_stats(rep_based, ["reps"]),
        "",
        "#### Reps — time-based only (reps < 0, stored as negative seconds)",
        "",
        f"Rows: {len(time_based):,}",
        "",
        numeric_stats(time_based, ["reps_abs"]),
        "",
        "> **Warning:** `reps_abs` max = 86,400 s (24 h). Cap at chunking time — values above ~3,600 s are almost certainly data errors.",
        "",
        "### Categorical column values",
        "",
        "#### `equipment` (single value per row)",
        "",
        "| Value | Rows | % |",
        "|---|---|---|",
        value_counts_table(detail["equipment"]),
        "",
        "#### `level` (stringified list — exploded counts)",
        "",
        "| Value | Programs | % of programs |",
        "|---|---|---|",
        list_col_counts(detail["level"]),
        "",
        "#### `goal` (stringified list — exploded counts)",
        "",
        "| Value | Programs | % of programs |",
        "|---|---|---|",
        list_col_counts(detail["goal"]),
        "",
        "> **Note:** `detail` has `At-Home & Calisthenics` as a goal value that does not appear in `program_summary`. Handle in chunking — map or keep as-is.",
        "",
        "#### `intensity` unique values",
        "",
        f"Integer 0–10: {sorted(detail['intensity'].dropna().astype(int).unique().tolist())}",
        "",
        "---",
        "",
    ]

    # ── program_summary ───────────────────────────────────────────────────────
    lines += [
        "## `program_summary.csv` — column reference",
        "",
        "### Column overview",
        "",
        "| Column | dtype | Description | Notes |",
        "|---|---|---|---|",
        "| `title` | str | Program name — joins to `title` in the detail file | Primary identifier |",
        "| `description` | str | Full program narrative (goals, structure, nutrition hints) | Main text for Designer RAG chunks; ~0.15% null |",
        "| `level` | str | Stringified Python list of difficulty levels | Same encoding as detail file |",
        "| `goal` | str | Stringified Python list of training goals | Same encoding as detail file |",
        "| `equipment` | str | Equipment category | 4 values; ~0.04% null |",
        "| `program_length` | float | Total program duration in weeks | ~0.04% null |",
        "| `time_per_workout` | float | Expected workout duration in minutes | No nulls |",
        "| `total_exercises` | int | Total exercise rows across all weeks/days | Range 1–5,040; outlier at top end |",
        "| `created` | str | Program creation timestamp | ~0.04% null |",
        "| `last_edit` | str | Last edit timestamp | ~0.08% null |",
        "",
        "### Missing values",
        "",
        "| Column | Null count | Null % |",
        "|---|---|---|",
        null_table(summary),
        "",
        "### Numeric column statistics",
        "",
        numeric_stats(summary, ["program_length", "time_per_workout", "total_exercises"]),
        "",
        "> **Warning:** `total_exercises` max = 5,040. P75 = 308. Programs above ~1,000 total exercises are almost certainly data errors — consider filtering.",
        "",
        "### Categorical column values",
        "",
        "#### `equipment`",
        "",
        "| Value | Programs | % |",
        "|---|---|---|",
        value_counts_table(summary["equipment"]),
        "",
        "#### `level` (stringified list — exploded counts)",
        "",
        "| Value | Programs | % of programs |",
        "|---|---|---|",
        list_col_counts(summary["level"]),
        "",
        "#### `goal` (stringified list — exploded counts)",
        "",
        "| Value | Programs | % of programs |",
        "|---|---|---|",
        list_col_counts(summary["goal"]),
        "",
        "---",
        "",
    ]

    # ── Qdrant payload mapping ────────────────────────────────────────────────
    lines += [
        "## Qdrant payload field mapping",
        "",
        "Confirmed field names to use in `vectorstore/schema.py` and `chunk_data.py`:",
        "",
        "| Payload field | Source column | Type after parsing | Used by |",
        "|---|---|---|---|",
        "| `source_table` | generated | `str`: `'exercises'` or `'programs'` | Retriever routing |",
        "| `title` | `title` | `str` | Foreign key / display |",
        "| `goal` | `goal` (parsed list) | `list[str]` | Slot filter |",
        "| `level` | `level` (parsed list) | `list[str]` | Slot filter |",
        "| `equipment` | `equipment` | `str` | Exact-match slot filter |",
        "| `program_length_weeks` | `program_length` | `int` | Slot filter |",
        "| `time_per_workout_min` | `time_per_workout` | `int` | Slot filter |",
        "| `exercise_name` | `exercise_name` | `str` | exercises table only |",
        "| `sets` | `sets` | `int` | exercises table only |",
        "| `reps` | `reps_abs` | `int` | exercises table only; store absolute value |",
        "| `is_time_based` | derived from `reps < 0` | `bool` | exercises table only |",
        "| `intensity` | `intensity` | `int` | exercises table only |",
        "| `chunk_id` | generated | `str` | UUID per chunk |",
        "| `text` | generated at chunk time | `str` | The embedded + returned text |",
        "",
        "---",
        "",
    ]

    # ── Chunking decisions ─────────────────────────────────────────────────────
    lines += [
        "## Chunking decisions",
        "",
        "### `programs_detailed_boostcamp_kaggle.csv` → exercises chunks",
        "",
        "- **Strategy:** one JSONL record per exercise row.",
        "- **Text field:** `f\"{exercise_name} | {sets} sets x {reps_display} | intensity {intensity}/10 | equipment: {equipment}\"`",
        "- **Skip:** rows where `exercise_name` is null.",
        "- **Clean:** cap `reps_abs` at 3,600 s for time-based rows; cap `sets` at 20.",
        "- **Payload:** `source_table`, `title`, `goal`, `level`, `equipment`, `program_length_weeks`, `exercise_name`, `sets`, `reps`, `is_time_based`, `intensity`.",
        "",
        "### `program_summary.csv` → program chunks",
        "",
        "- **Strategy:** one JSONL record per program, combining narrative fields.",
        "- **Text field:** `title + description + goal + level + equipment + program_length`",
        "  (from `config.settings.PROGRAM_CHUNK_FIELDS`).",
        "- **Skip:** rows where `description` is null.",
        "- **Payload:** `source_table`, `title`, `goal`, `level`, `equipment`, `program_length_weeks`, `time_per_workout_min`, `total_exercises`.",
        "",
    ]

    DATA_SCHEMA_DIR.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Written → {OUT_PATH}  ({OUT_PATH.stat().st_size / 1024:.1f} KB)")
    print("Next step: python scripts/chunk_data.py")


if __name__ == "__main__":
    main()
